# # check that a type cannot be changed in python
# print("TypeError: 'tuple' object does not support item assignment\n they are immutable\n")

# a = (34,234,"harry")

# a[2] = "Jerry"

# # wap to num a list with 4 numbers..
# num = []
# f1  = int(input("Enter num 1here : ")) 
# num.append(f1)
# f2  = int(input("Enter num2 here : ")) 
# num.append(f2)
# f3  = int(input("Enter num3 here : ")) 
# num.append(f3)
# f4  = int(input("Enter num4 here : ")) 
# num.append(f4)

# print("f1+f2+f3+f4 =",f1+f2+f3+f4)

# # wap to count the number od zeroes in the following tuple :

a =(7,0,8,0,0,9)
n = a.count(0)
print(n)
















